### ISSUE TITLE
Running the trained model on other point clouds directly

### ISSUE THREAD

**Issue by mostafaashraf97** [chenghao-shi/MDGAT-matcher#11]
Hello Chenghao, 

I am new in doing all this and I want to use MDGAT to estimate poses from point cloud data. I don't understand quite well the descriptors and keypoints part. but my question is can I use the trained model to estimate poses using calculate error function so that it can be used later for other stuff or not? Thanks in advance.

**Comment by chenghao-shi** [comment]
Hi!

MDGAT is developed as a keypoint matcher, which means it relies on pre-extracted points with descriptors to be matched. This model is trained on USIP keypoints with FPFH descriptors. You can test on your point clouds following above configuration. For more detailed information, please refer to #10. 

 Also, we have developed another repository for end-to-end direct estimation of relative poses between point clouds without the need for pre-extracting keypoints and descriptors. This repository will be open-sourced in the near future. If you are interested, please follow this [link](https://github.com/nubot-nudt/RDMNet).

**Comment by mostafaashraf97** [comment]
Hello,

Thank you for the fast reply. I will try to extract the keypoints myself then following the steps you mentioned. That other repository is actually exactly what I need and would be great to use it once it comes out. do you have an estimated date on when would it be released? Thank you in advance and best of luck.

**Comment by chenghao-shi** [comment]
Hi,

The code will be released in August. Thank you for your interest.

**Comment by mostafaashraf97** [comment]
Hello again, 

I was able to get the input data as mentioned in the other issue [x,y,z,score,33dim fpfh] but the issue is to pass that into mdgat i need ground truths which i do not have so I created them as ones as well as score is also set to constant value is that correct in regard to the output i get from mdgat model or not and if not is there a way not to pass ground truth in the input dict ? Thanks again for your help, i really appreciate it
